CREATE TABLE IF NOT EXISTS comments
(
    comment_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    comment_created TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    text            VARCHAR(7000)                           NOT NULL,
    status          VARCHAR(50)                             NOT NULL,
    user_id         BIGINT,
    event_id        BIGINT,
    CONSTRAINT pk_comments PRIMARY KEY (comment_id),
    CONSTRAINT fk_comments_on_users FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_comments_on_events FOREIGN KEY (event_id) REFERENCES events (event_id)
);

CREATE INDEX IF NOT EXISTS comments_user_id_idx on comments (user_id);
CREATE INDEX IF NOT EXISTS comments_event_id_idx on comments (event_id);